#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2019.4.9f1_50fe8a171dd9"
#define UNITY_VERSION_FULL_NICE "2019.4.9f1 (50fe8a171dd9)"
#define UNITY_VERSION_BLD 5308042
#define UNITY_VERSION_DATE 1597716551
#define UNITY_VERSION_WIN "2019.4.9.5308042"
#define UNITY_VERSION_BRANCH "2019.4/staging"
